services:
  - type: web
    name: room-booking-app
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: mongodb+srv://shopb69x_db_user:Uh6H4TzhIAVWdiF1@cluster0.fxkw8ys.mongodb.net/room_booking?retryWrites=true&w=majority&appName=Cluster0
